{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aviralworld.fullname" . }}-frontend
  labels:
{{ include "aviralworld.labels" . | indent 4 }}
    app: frontend
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "aviralworld.selectorLabels" . | nindent 6 }}
      app: frontend
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "aviralworld.selectorLabels" . | nindent 8 }}
        app: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aviralworld.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: app
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.frontend.adminPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthz
              port: admin
            failureThreshold: 12
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              value: "{{ .Values.frontend.port }}"
            - name: FRONTEND_BASE_URL
              value: "{{ .Values.frontend.baseUrl }}"
            - name: FRONTEND_API_URL
              value: "http://{{ include "aviralworld.fullname" . }}-backend:{{ .Values.backend.port }}" # "
            - name: NODE_ENV
              value: "{{ .Values.frontend.environment }}"
            - name: FRONTEND_RANDOM_STORY_COUNT
              value: "{{ .Values.frontend.randomStoryCount }}"
            - name: FRONTEND_ENABLE_ADMIN_MODE
              value: {{ if .Values.frontend.enableAdminMode }}"1"{{ else }}"0"{{ end }}
            - name: FRONTEND_DEBOUNCE_DELAY_MS
              value: "{{ .Values.frontend.debounceDelayMs }}"
            - name: FRONTEND_SERVE_STATIC
              value: "0"
            - name: FRONTEND_COMPRESSION
              value: "0"
            - name: FRONTEND_ADMIN_PORT
              value: "{{ .Values.frontend.adminPort }}"
            - name: FRONTEND_HEALTH_CHECK_TIMEOUT_MS
              value: "{{ .Values.frontend.healthCheckTimeoutMs }}"
            - name: FRONTEND_MAX_RECORDING_LENGTH_SECONDS
              value: "{{ .Values.frontend.maxRecordingLength }}"
            - name: FRONTEND_MIN_RECORDING_LENGTH_SECONDS
              value: "{{ .Values.frontend.minRecordingLength }}"
            - name: ROARR_LOG
              value: "true"
            {{ include "aviralworld.newrelic" . | nindent 12 }}
        - name: {{ .Chart.Name }}-frontend-http
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}/http:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /static/logo.svg
              port: nginx
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: FRONTEND_APP_URL
              value: "http://127.0.0.1:{{ .Values.frontend.port }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}