apiVersion: v1
kind: Service
metadata:
  name: {{ include "aviralworld.fullname" . }}-frontend
  labels:
{{ include "aviralworld.labels" . | indent 4 }}
    app: frontend
spec:
  type: "{{ .Values.frontend.service.type }}"
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: nginx
      protocol: TCP
      name: http
  selector:
    {{- include "aviralworld.selectorLabels" . | nindent 4 }}
    app: frontend
