image:
  tag: "v2.4.8"

ports:
  websecure:
    tls:
      enabled: true

globalArguments:
  - "--global.checknewversion"

additionalArguments:
  - "--providers.kubernetesIngress.ingressClass=traefik-cert-manager"
  - "--providers.kubernetescrd.allowCrossNamespace=false"
  - "--ping"
  - "--metrics.prometheus"
