ingressRoute:
  dashboard:
    enabled: true

additionalArguments:
  - "--log.level=ERROR"
  - "--entrypoints.websecure.http.tls"
  - "--providers.kubernetesIngress.ingressClass=traefik-cert-manager"
  - "--ping"
  - "--metrics.prometheus"
